#!/bin/csh -f

set theradio=
set n=1
foreach radio ( `cat ttys.txt` `echo /dev/cu.usbserial*` `echo /dev/ttyUSB*` /dev/null /dev/null )
 echo "Radio $n is $radio"
 if ( $n == $1 ) then
    set theradio=$radio
 endif
 @ n = $n + 1
end

#setenv MallocStackLogging 1
#setenv MallocStackLoggingNoCompact 1
#setenv MallocScribble 1
#setenv MallocPreScribble 1
#setenv MallocGuardEdges 1
#setenv MallocCheckHeapStart 1
#setenv MallocCheckHeapEach 1
    
echo ./lbard 127.0.0.1:`cat testing/serval${1}/proc/http_port` lbard:lbard `cat testing/serval${1}/self.id | cut -f 1 -d:` `cat testing/serval${1}/self.id | cut -f 2 -d:` $theradio announce pull
./lbard 127.0.0.1:`cat testing/serval${1}/proc/http_port` lbard:lbard `cat testing/serval${1}/self.id | cut -f 1 -d:` `cat testing/serval${1}/self.id | cut -f 2 -d:`  $theradio bundlelog=bundlelog${1}.txt $2
 
