#!/bin/csh -f

if ( -e testing ) then
  cd testing
endif

foreach instance ( serval? )
 # Stop relevant servald instance

 cd $instance
 setenv SERVALINSTANCE_PATH `pwd`
 echo ""
 echo "---------------------------------------------------------------------"
 echo "Instance $instance"
 echo "---------------------------------------------------------------------"
 ../../serval-dna/servald rhizome list
 ../../serval-dna/servald keyring list
 cd ..

end 
